### ISSUE TITLE
NotImplementedError: Cannot copy out of meta tensor; no data!

### ISSUE THREAD

**Issue by 4ku** [Meituan-AutoML/MobileVLM#7]
Have this error, when trying to make inference on `MobileVLM-3B`:
```
Traceback (most recent call last):
  File "/home/ivan/Desktop/projects/MobileVLM/main.py", line 22, in <module>
    inference_once(args)
  File "/home/ivan/Desktop/projects/MobileVLM/scripts/inference.py", line 19, in inference_once
    tokenizer, model, image_processor, context_len = load_pretrained_model(args.model_path)
  File "/home/ivan/Desktop/projects/MobileVLM/mobilevlm/model/mobilevlm.py", line 261, in load_pretrained_model
    vision_tower.to(device=device, dtype=torch.float16)
  File "/home/ivan/anaconda3/envs/mobilevlm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1145, in to
    return self._apply(convert)
  File "/home/ivan/anaconda3/envs/mobilevlm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/home/ivan/anaconda3/envs/mobilevlm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/home/ivan/anaconda3/envs/mobilevlm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  [Previous line repeated 1 more time]
  File "/home/ivan/anaconda3/envs/mobilevlm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 820, in _apply
    param_applied = fn(param)
  File "/home/ivan/anaconda3/envs/mobilevlm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1143, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
NotImplementedError: Cannot copy out of meta tensor; no data!
```

With `MobileVLM-1.7B` everything is ok.

**Comment by er-muyue** [comment]
I guess the most likely reason is insufficient remaining memory on the GPU. Have you checked the memory status while running the MobileVLM-3B model?  (OR) Can the solution mentioned [here](https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/13087#issuecomment-1710361268) solve your problem? If not, could you please provide more information of your GPU cards and environment?

**Comment by 4ku** [comment]
`--disable-model-loading-ram-optimization` is a special flag for `stable-diffusion-webui` project, which `MobileVLM` obviously doesn't have.

I have GPU with 4GB:
```
nvidia-smi 
Sat Jan  6 19:30:13 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.129.03             Driver Version: 535.129.03   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 3050 ...    On  | 00000000:01:00.0 Off |                  N/A |
| N/A   42C    P0              N/A /  60W |      9MiB /  4096MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A      2560      G   /usr/lib/xorg/Xorg                            4MiB |
+---------------------------------------------------------------------------------------+
```

Maybe I should run `MobileVLM-3B` on the CPU? How to do that?

**Comment by er-muyue** [comment]
MobileVLM-3B inference with fp16 requires 7.6G memory at least. The 4bit-inference is supported [here](https://github.com/Meituan-AutoML/MobileVLM/blob/0a2a1c81a66d0a5d5affaadae924091467116218/scripts/inference.py#L66). You can turn on 4bit-inference(set `load_4bit=True`), so that the MobileVLM-3B model requires approximately 4GB of running memory.

**Comment by 4ku** [comment]
Thank you, it works!
